# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  workflow_dispatch:
  release:
    types:
      - published # Run when a new GitHub release is published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  BuildDirectory: ${{ github.workspace }}/LanguageExt.AspNetCore.NativeTypes/LanguageExt.AspNetCore.NativeTypes/bin/Release
  NuGetDirectory: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - uses: actions/upload-artifact@v3
      with:
        name: build
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.BuildDirectory }}

  pack:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: build
        path: ${{ env.BuildDirectory }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Package
      run: dotnet pack --configuration Release --no-build --output "${{ env.NuGetDirectory }}"
    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg

  publish:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ pack ]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nuget
        path: ${{ env.NuGetDirectory }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
    - name: Publish
      run: |
        Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg `
          | %{dotnet nuget push "$_" --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate}